on:
  pull_request:
    types: [closed]
    branches:
      - main
name: 🚀 Deploy website to prod on merge
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: Install dependencies and run Gulp on plugin
        working-directory: "./wp-content/plugins/dentaly-core/"
        run: |
          npm i
          gulp build
          rm -rf node_modules
      - name: Upload All Files
        uses: appleboy/scp-action@master
        with:
          timeout: 200s
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_LOGIN }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "wp-content/*"
          target: "~/public_html"
