name: 🚀 Deploy website to staging on merge
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Upload All Files
        uses: appleboy/scp-action@master
        with:
          timeout: 200s
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_LOGIN }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "wp-content/*"
          target: "~/public_html"
